language: php

sudo: false

# install required system packages, see 'install' below for details
# Travis' containers require this, otherwise use this:
# sudo apt-get install openssl build-essential libev-dev libssl-dev
addons:
  apt:
    packages:
    - openssl
    - build-essential
    - libev-dev
    - libssl-dev


install:
    # start a web server on port 8080, running in the background
    - php -S 127.0.0.1:8080 -t "$TRAVIS_BUILD_DIR/tests/web" > /dev/null 2> "$TRAVIS_BUILD_DIR/server.log" &

    # we need openssl and either stunnel or stud
    # unfortunately these are not available in Travis' containers
    # sudo apt-get install -y openssl stud
    # sudo apt-get install -y openssl stunnel4

    # instead, let's install stud from source
    # build dependencies are already installed, see 'addons.apt.packages' above
    # sudo apt-get install openssl build-essential libev-dev libssl-dev
    - git clone https://github.com/bumptech/stud.git
    - (cd stud && make)

    # create self-signed certificate
    - openssl genrsa 1024 > stunnel.key
    - openssl req -batch -subj '/CN=127.0.0.1' -new -x509 -nodes -sha1 -days 3650 -key stunnel.key > stunnel.cert
    - cat stunnel.cert stunnel.key > stunnel.pem

    # start TLS/SSL terminating proxy
    - ./stud/stud --daemon -f 127.0.0.1,8181 -b 127.0.0.1,8080 stunnel.pem


matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - php: 5.6
        - php: 5.6
          env: deps=low
        - php: 7.0
        - php: hhvm
        - php: nightly
        - php: nightly
          env: deps=low

before_script:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;'
    - composer self-update
    - if [[ $deps = low ]]; then composer update --no-interaction --prefer-lowest ; fi
    - if [[ !$deps ]]; then composer install --no-interaction ; fi

script:
    - vendor/bin/behat -fprogress --strict

after_failure:
    - cat server.log
